version: "3"

services:
  golang:
    tty: true
    build: "./app"
    volumes:
      - .:/app
    ports:
      - 3000
  nginx:
    build: ./nginx
    ports:
      - 8001:80
    depends_on:
      - "golang"